#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.9
# from Racc grammer file "".
#

require 'racc/parser.rb'
module Vimitator
  class Parser < Racc::Parser

module_eval(<<'...end parser.racc/module_eval...', 'parser.racc', 94)
  def parse(tokens)
    @yydebug = true
    @tokens = tokens
    do_parse
  end

  #def on_error( *args )
  #  $stderr.puts "on_error called: args=#{args.inspect}"
  #end

  def next_token
    token = @tokens.shift
    #puts "Token: #{token.inspect}"
    token
  end
...end parser.racc/module_eval...
##### State transition tables begin ###

racc_action_table = [
    88,    80,   106,    13,    14,    17,    18,    20,    22,    23,
    73,    73,    73,    31,    32,    33,    34,    77,    77,    35,
    32,   108,    36,    37,    13,    14,    17,    18,    20,    22,
    23,    90,    73,    85,    31,    32,    33,    34,   103,    41,
    35,    91,    52,    36,    37,    13,    14,    17,    18,    20,
    22,    23,   -78,    77,    34,    31,    32,    33,    34,    73,
    73,    35,    32,    73,    36,    37,   100,    13,    14,    17,
    18,    20,    22,    23,    73,    75,    69,    31,    32,    33,
    34,    73,    77,    35,    73,    79,    36,    37,    93,    13,
    14,    17,    18,    20,    22,    23,    69,    79,    74,    31,
    32,    33,    34,   102,    73,    35,    73,    71,    36,    37,
    13,    14,    17,    18,    20,    22,    23,    73,    66,    39,
    31,    32,    33,    34,    38,    73,    35,   110,    73,    36,
    37,    13,    14,    17,    18,    20,    22,    23,   nil,   nil,
   nil,    31,    32,    33,    34,   nil,   nil,    35,   nil,   nil,
    36,    37,    13,    14,    17,    18,    20,    22,    23,   nil,
   nil,   nil,    31,    32,    33,    34,   nil,   nil,    35,   nil,
   nil,    36,    37,    13,    14,    17,    18,    20,    22,    23,
    48,   nil,   nil,    31,    32,    33,    34,   nil,   nil,    35,
   nil,   nil,    36,    37,    13,    14,    17,    18,    20,    22,
    23,   nil,   nil,   nil,    31,    32,    33,    34,   nil,   nil,
    35,   nil,   nil,    36,    37,    13,    14,    17,    18,    20,
    22,    23,   nil,   nil,   nil,    31,    32,    33,    34,   nil,
   nil,    35,   nil,   nil,    36,    37,    13,    14,    17,    18,
    20,    22,    23,   nil,   nil,   nil,    31,    32,    33,    34,
   nil,   nil,    35,   nil,   nil,    36,    37,    13,    14,    17,
    18,    20,    22,    23,   nil,   nil,   nil,    31,    32,    33,
    34,   nil,    69,    35,   nil,   nil,    36,    37,    13,    14,
    17,    18,    20,    22,    23,   nil,   nil,   nil,    31,    32,
    33,    34,   nil,   nil,    35,   nil,   nil,    36,    37,    13,
    14,    17,    18,    20,    22,    23,   nil,   nil,   nil,    31,
    32,    33,    34,   nil,   nil,    35,   nil,   nil,    36,    37,
    13,    14,    17,    18,    20,    22,    23,   nil,   nil,   nil,
    31,    32,    33,    34,    56,   nil,    35,   nil,   nil,    36,
    37,   nil,    55,    57,    31,   nil,    33 ]

racc_action_check = [
    68,    51,    99,    68,    68,    68,    68,    68,    68,    68,
    63,    65,    64,    68,    68,    68,    68,    99,    51,    68,
    42,   101,    68,    68,   101,   101,   101,   101,   101,   101,
   101,    70,    42,    67,   101,   101,   101,   101,    92,     4,
   101,    70,    27,   101,   101,    27,    27,    27,    27,    27,
    27,    27,     4,    92,     4,    27,    27,    27,    27,    62,
    61,    27,    54,    60,    27,    27,    83,    83,    83,    83,
    83,    83,    83,    83,    54,    47,    78,    83,    83,    83,
    83,    82,    47,    83,    78,    50,    83,    83,    72,    72,
    72,    72,    72,    72,    72,    72,    86,    84,    46,    72,
    72,    72,    72,    87,    86,    72,    89,    41,    72,    72,
    25,    25,    25,    25,    25,    25,    25,    96,    38,     2,
    25,    25,    25,    25,     1,   105,    25,   107,   109,    25,
    25,     7,     7,     7,     7,     7,     7,     7,   nil,   nil,
   nil,     7,     7,     7,     7,   nil,   nil,     7,   nil,   nil,
     7,     7,     6,     6,     6,     6,     6,     6,     6,   nil,
   nil,   nil,     6,     6,     6,     6,   nil,   nil,     6,   nil,
   nil,     6,     6,    26,    26,    26,    26,    26,    26,    26,
    26,   nil,   nil,    26,    26,    26,    26,   nil,   nil,    26,
   nil,   nil,    26,    26,     5,     5,     5,     5,     5,     5,
     5,   nil,   nil,   nil,     5,     5,     5,     5,   nil,   nil,
     5,   nil,   nil,     5,     5,    81,    81,    81,    81,    81,
    81,    81,   nil,   nil,   nil,    81,    81,    81,    81,   nil,
   nil,    81,   nil,   nil,    81,    81,    97,    97,    97,    97,
    97,    97,    97,   nil,   nil,   nil,    97,    97,    97,    97,
   nil,   nil,    97,   nil,   nil,    97,    97,    40,    40,    40,
    40,    40,    40,    40,   nil,   nil,   nil,    40,    40,    40,
    40,   nil,    40,    40,   nil,   nil,    40,    40,    76,    76,
    76,    76,    76,    76,    76,   nil,   nil,   nil,    76,    76,
    76,    76,   nil,   nil,    76,   nil,   nil,    76,    76,    59,
    59,    59,    59,    59,    59,    59,   nil,   nil,   nil,    59,
    59,    59,    59,   nil,   nil,    59,   nil,   nil,    59,    59,
     0,     0,     0,     0,     0,     0,     0,   nil,   nil,   nil,
     0,     0,     0,     0,    28,   nil,     0,   nil,   nil,     0,
     0,   nil,    28,    28,    28,   nil,    28 ]

racc_action_pointer = [
   314,   124,   117,   nil,    35,   188,   146,   125,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   104,   167,    39,   328,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   118,   nil,
   251,    91,     3,   nil,   nil,   nil,    93,    62,   nil,   nil,
    72,    -2,   nil,   nil,    45,   nil,   nil,   nil,   nil,   293,
    34,    31,    30,   -19,   -17,   -18,   nil,    30,    -3,   nil,
    25,   nil,    83,   nil,   nil,   nil,   272,   nil,    55,   nil,
   nil,   209,    52,    61,    84,   nil,    75,   100,   nil,    77,
   nil,   nil,    33,   nil,   nil,   nil,    88,   230,   nil,    -3,
   nil,    18,   nil,   nil,   nil,    96,   nil,   124,   nil,    99,
   nil ]

racc_action_default = [
   -80,   -80,   -80,    -2,    -3,   -80,   -80,   -80,    -7,    -8,
    -9,   -10,   -11,   -20,   -21,   -22,   -23,   -24,   -25,   -26,
   -27,   -28,   -29,   -30,   -31,   -80,   -80,   -80,   -44,   -45,
   -53,   -54,   -78,   -78,   -78,   -78,   -78,   -78,   -80,    -1,
   -80,   -80,   -80,    -4,    -5,    -6,   -80,   -80,   -34,   -35,
   -78,   -80,   -39,   -78,   -80,   -46,   -47,   -48,   -49,   -80,
   -63,   -65,   -67,   -71,   -74,   -75,   111,   -78,   -80,   -78,
   -17,   -50,   -80,   -79,   -32,   -33,   -80,   -78,   -80,   -55,
   -38,   -80,   -42,   -80,   -80,   -12,   -80,   -80,   -16,   -70,
   -51,   -52,   -80,   -19,   -36,   -78,   -69,   -80,   -78,   -80,
   -41,   -80,   -14,   -18,   -78,   -43,   -40,   -80,   -15,   -37,
   -13 ]

racc_goto_table = [
     2,    51,    49,    68,    42,    72,    43,    44,    45,     1,
    70,    59,    47,    40,    76,    58,   nil,    83,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    46,    50,   nil,    54,   nil,
   nil,   nil,    60,    61,    62,    63,    64,    65,   nil,   nil,
    67,    97,   nil,   nil,   nil,   nil,    92,   nil,   nil,   101,
   nil,   nil,    94,    82,   nil,   nil,   nil,    99,   nil,    84,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    86,    87,    89,
   nil,   nil,   nil,   nil,   nil,   nil,    95,    96,   nil,   nil,
   nil,    98,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   104,   105,   nil,
   nil,   107,   nil,   nil,   109 ]

racc_goto_check = [
     2,    18,    26,    15,    14,    17,     3,     3,     3,     1,
    16,    24,    25,    13,    27,    29,   nil,    17,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,     2,     2,   nil,    14,   nil,
   nil,   nil,    14,    14,    14,    14,    14,    14,   nil,   nil,
     2,    15,   nil,   nil,   nil,   nil,    18,   nil,   nil,    15,
   nil,   nil,    26,    14,   nil,   nil,   nil,    18,   nil,     2,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    14,     2,    14,
   nil,   nil,   nil,   nil,   nil,   nil,     2,    14,   nil,   nil,
   nil,     2,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,     2,    14,   nil,
   nil,     2,   nil,   nil,    14 ]

racc_goto_pointer = [
   nil,     9,     0,     1,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,     9,     0,   -37,   -31,   -37,   -26,   nil,
   nil,   nil,   nil,   nil,   -17,   -14,   -24,   -33,   nil,   -13,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil ]

racc_goto_default = [
   nil,   nil,    53,     3,     4,     5,     6,     7,     8,     9,
    10,    11,    12,    27,    78,   nil,   nil,    25,   nil,    15,
    16,    19,    21,    24,    26,   nil,   nil,    81,    28,    29,
    30,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  2, 31, :_reduce_none,
  1, 32, :_reduce_none,
  1, 33, :_reduce_none,
  2, 33, :_reduce_none,
  2, 33, :_reduce_none,
  2, 33, :_reduce_none,
  1, 34, :_reduce_none,
  1, 34, :_reduce_none,
  1, 34, :_reduce_none,
  1, 34, :_reduce_none,
  1, 34, :_reduce_none,
  4, 42, :_reduce_none,
  7, 41, :_reduce_none,
  5, 41, :_reduce_none,
  6, 41, :_reduce_none,
  4, 41, :_reduce_none,
  3, 40, :_reduce_none,
  5, 39, :_reduce_none,
  4, 39, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  3, 53, :_reduce_none,
  3, 52, :_reduce_none,
  2, 52, :_reduce_none,
  1, 55, :_reduce_none,
  3, 55, :_reduce_none,
  5, 56, :_reduce_none,
  3, 51, :_reduce_none,
  2, 51, :_reduce_none,
  5, 49, :_reduce_none,
  4, 49, :_reduce_none,
  2, 48, :_reduce_none,
  4, 48, :_reduce_none,
  1, 50, :_reduce_none,
  1, 58, :_reduce_none,
  2, 58, :_reduce_none,
  2, 58, :_reduce_none,
  2, 58, :_reduce_none,
  2, 58, :_reduce_none,
  1, 46, :_reduce_none,
  2, 46, :_reduce_none,
  2, 46, :_reduce_none,
  1, 59, :_reduce_none,
  1, 59, :_reduce_none,
  3, 60, :_reduce_none,
  2, 61, :_reduce_none,
  2, 61, :_reduce_none,
  2, 62, :_reduce_none,
  2, 63, :_reduce_none,
  2, 64, :_reduce_none,
  2, 65, :_reduce_none,
  2, 65, :_reduce_none,
  2, 47, :_reduce_none,
  2, 66, :_reduce_none,
  2, 54, :_reduce_none,
  2, 67, :_reduce_none,
  2, 43, :_reduce_none,
  2, 68, :_reduce_none,
  2, 57, :_reduce_none,
  2, 45, :_reduce_none,
  2, 35, :_reduce_none,
  2, 69, :_reduce_none,
  2, 70, :_reduce_none,
  2, 37, :_reduce_none,
  2, 36, :_reduce_none,
  2, 71, :_reduce_none,
  2, 72, :_reduce_none,
  0, 44, :_reduce_none,
  2, 44, :_reduce_none ]

racc_reduce_n = 80

racc_shift_n = 111

racc_token_table = {
  false => 0,
  :error => 1,
  :END => 2,
  :RSQUARE => 3,
  :DOT => 4,
  :RPAREN => 5,
  :NUMBER => 6,
  :FLOAT => 7,
  :REGISTER => 8,
  :ENVVAR => 9,
  :OPTION => 10,
  :SQSTRING => 11,
  :DQSTRING => 12,
  :RCURLY => 13,
  :NAMESPACE => 14,
  :HASH => 15,
  :HEAD => 16,
  :LPAREN => 17,
  :LCURLY => 18,
  :LSQUARE => 19,
  :COMMA => 20,
  :COLON => 21,
  :NOT => 22,
  :AND => 23,
  :OR => 24,
  :PLUS => 25,
  :MINUS => 26,
  :STAR => 27,
  :MODULE => 28,
  :WHITE => 29 }

racc_nt_base = 30

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "END",
  "RSQUARE",
  "DOT",
  "RPAREN",
  "NUMBER",
  "FLOAT",
  "REGISTER",
  "ENVVAR",
  "OPTION",
  "SQSTRING",
  "DQSTRING",
  "RCURLY",
  "NAMESPACE",
  "HASH",
  "HEAD",
  "LPAREN",
  "LCURLY",
  "LSQUARE",
  "COMMA",
  "COLON",
  "NOT",
  "AND",
  "OR",
  "PLUS",
  "MINUS",
  "STAR",
  "MODULE",
  "WHITE",
  "$start",
  "vimexpr",
  "expr",
  "expr7",
  "expr8",
  "not",
  "minus",
  "plus",
  "expr9",
  "funcrefcall",
  "dictdot",
  "idxrange",
  "index",
  "lsquare",
  "space",
  "colon",
  "word",
  "lparen",
  "exprlist",
  "funccall",
  "variable",
  "list",
  "dictionary",
  "nested",
  "lcurly",
  "dictlist",
  "dictitem",
  "comma",
  "ident",
  "startofident",
  "braceident",
  "number",
  "register",
  "option",
  "envvariable",
  "string",
  "rparen",
  "rcurly",
  "rsquare",
  "and",
  "or",
  "star",
  "mod" ]

Racc_debug_parser = true

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

# reduce 21 omitted

# reduce 22 omitted

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

# reduce 29 omitted

# reduce 30 omitted

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

# reduce 36 omitted

# reduce 37 omitted

# reduce 38 omitted

# reduce 39 omitted

# reduce 40 omitted

# reduce 41 omitted

# reduce 42 omitted

# reduce 43 omitted

# reduce 44 omitted

# reduce 45 omitted

# reduce 46 omitted

# reduce 47 omitted

# reduce 48 omitted

# reduce 49 omitted

# reduce 50 omitted

# reduce 51 omitted

# reduce 52 omitted

# reduce 53 omitted

# reduce 54 omitted

# reduce 55 omitted

# reduce 56 omitted

# reduce 57 omitted

# reduce 58 omitted

# reduce 59 omitted

# reduce 60 omitted

# reduce 61 omitted

# reduce 62 omitted

# reduce 63 omitted

# reduce 64 omitted

# reduce 65 omitted

# reduce 66 omitted

# reduce 67 omitted

# reduce 68 omitted

# reduce 69 omitted

# reduce 70 omitted

# reduce 71 omitted

# reduce 72 omitted

# reduce 73 omitted

# reduce 74 omitted

# reduce 75 omitted

# reduce 76 omitted

# reduce 77 omitted

# reduce 78 omitted

# reduce 79 omitted

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module Vimitator
